title: CyberArk
description:  This site serves as a comprehensive guide for all things related to CyberArk, including installation, configuration, and scripting.
theme: just-the-docs
markdown: kramdown
kramdown:
  input: GFM


url: "https://ehtishammushtaq.github.io" # the base hostname & protocol for your site



aux_links:
  Ehtisham Mushtaq: https://github.com/Ehtishammushtaq
